version: '3'
services:
  mysql-wordpress:
    image: mysql
    restart: unless-stopped
    container_name: mysql-wordpress
    environment:
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${WP_DB_PASSWORD}
    volumes:
      - /data/mysql-wordpress:/var/lib/mysql
  wordpress:
    image: wordpress
    restart: unless-stopped
    container_name: wordpress
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=${WP_DB_HOST}
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
    volumes:
      - /data/wordpress:/var/www/html
    depends_on:
      - mysql-wordpress
